// URLs built from an event: flyer image, its own page, Google Calendar, Google Maps and WhatsApp share.

import type { DanceEvent, EventMedia } from "../types";
import { addDays } from "./dates";
import { formatLongDate, formatTime, placeLabel, priceSummary } from "./format";

export const BASE_URL = import.meta.env.BASE_URL.replace(/\/?$/, "/");
const SITE_URL = new URL(BASE_URL, import.meta.env.SITE).href; // "https://pa-bailar.github.io/"
const DEFAULT_DURATION_HOURS = 4; // socials often run past midnight

export function flyerUrl(media: EventMedia): string | null {
  return media.flyer ? `${BASE_URL}${media.flyer}` : null;
}

/** The main post: the one shown on the card and shared by default. */
export function mainMedia(event: DanceEvent): EventMedia {
  return event.media[0];
}

/** Path (under the site root) of the event's link-preview image, made by pages/og/[id].jpg.ts. */
export function previewImagePath(event: DanceEvent): string | null {
  return mainMedia(event).flyer ? `og/${encodeURIComponent(event.id)}.jpg` : null;
}

/** Path of the event's own page ("/evento/<id>/"), generated by pages/evento/[id].astro. */
export function eventPath(event: DanceEvent): string {
  return `${BASE_URL}evento/${encodeURIComponent(event.id)}/`;
}

/** Full URL of the event's page, for sharing and calendars. */
export function eventPageUrl(event: DanceEvent): string {
  return new URL(eventPath(event), SITE_URL).href;
}

export interface EventTimes {
  start: string; // "YYYYMMDD" (all day) or "YYYYMMDDTHHMMSS" (Bogotá local time)
  end: string;
  allDay: boolean;
}

/**
 * Start and end for calendars. Without a start time it's an all-day event; without an end time it
 * lasts DEFAULT_DURATION_HOURS; an end before the start means it finishes after midnight.
 */
export function eventTimes(event: DanceEvent): EventTimes {
  const day = event.date.replaceAll("-", "");
  const nextDay = addDays(event.date, 1).replaceAll("-", "");
  if (!event.start_time) return { start: day, end: nextDay, allDay: true };

  const startHour = Number(event.start_time.slice(0, 2));
  const endTime =
    event.end_time ??
    `${String((startHour + DEFAULT_DURATION_HOURS) % 24).padStart(2, "0")}:${event.start_time.slice(3)}`;
  const endDay = endTime <= event.start_time ? nextDay : day;
  return {
    start: `${day}T${event.start_time.replace(":", "")}00`,
    end: `${endDay}T${endTime.replace(":", "")}00`,
    allDay: false,
  };
}

/** Text for the location field of calendars and maps. */
export function locationText(event: DanceEvent): string {
  return [event.venue, event.address, event.area, "Bogotá"].filter(Boolean).join(", ");
}

export function googleCalendarUrl(event: DanceEvent): string {
  const { start, end } = eventTimes(event);
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: event.title,
    dates: `${start}/${end}`,
    ctz: "America/Bogota",
    details: [eventPageUrl(event), ...event.media.map((media) => media.permalink)].join("\n"),
    location: locationText(event),
  });
  return `https://calendar.google.com/calendar/render?${params}`;
}

/** Google Maps search for the venue, or null when the post gives no venue or address. */
export function mapsUrl(event: DanceEvent): string | null {
  if (!event.venue && !event.address) return null;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(locationText(event))}`;
}

/** Ready-to-send message for the WhatsApp groups. It links to the event's page, whose preview shows the flyer. */
export function whatsappShareUrl(event: DanceEvent): string {
  const time = event.start_time ? ` · ${formatTime(event.start_time)}` : "";
  const lines = [
    `*${event.title}*`,
    `${formatLongDate(event.date)}${time}`,
    placeLabel(event),
    priceSummary(event),
    // Tagged so visits from these messages count as coming from WhatsApp (its app hides the referrer).
    `${eventPageUrl(event)}?utm_source=whatsapp`,
  ];
  return `https://wa.me/?text=${encodeURIComponent(lines.filter(Boolean).join("\n"))}`;
}
