// URLs built from an event: flyer image, its own page, Google Maps, the report form, and calendar times.

import type { DanceEvent, EventMedia, Session, View } from "../types";
import { addDays, isMultiDay, isSeries, lastDay } from "./dates";
import { eventDaysLabel, formatTime, priceSummary } from "./format";

export const BASE_URL = import.meta.env.BASE_URL.replace(/\/?$/, "/");
const SITE_URL = new URL(BASE_URL, import.meta.env.SITE).href; // "https://pa-bailar.github.io/"
const DEFAULT_DURATION_HOURS = 4; // socials often run past midnight
// Reports and ideas go to a Google Form (owned by the site's author): no account needed, answers land in a
// Google Sheet. From an event's detail, its "Evento" question comes filled in (a pre-filled link's entry).
const FEEDBACK_FORM = "https://docs.google.com/forms/d/e/1FAIpQLScMjLlDsXBdgqNGjs3MIBhuMKQhG7xZpdAyzlA5lHxH7OiXtw/viewform";
const FEEDBACK_EVENT_FIELD = "entry.1000168347";

/** The thumbnails' size and quality (pages/thumbs/[name].webp.ts): square, sharp on 2× and 3× screens at the ~60 px
 * they're shown. Part of their URL's version, so new settings reach returning visitors. */
export const THUMB_SIZE = 160;
export const THUMB_QUALITY = 70;

/** `?v=<version>`: a short hash of the flyer's file (src/images.ts), so one made again under its name gets a new URL. */
const versioned = (path: string, version: string | undefined) => (version ? `${path}?v=${version}` : path);

export function flyerUrl(media: EventMedia): string | null {
  return media.flyer ? versioned(`${BASE_URL}${media.flyer}`, media.version) : null;
}

/** "flyers/123-0.webp" → "123-0": the name of its small thumbnail, made by pages/thumbs/[name].webp.ts. */
export function thumbName(flyer: string): string {
  return flyer.replace(/^.*\//, "").replace(/\.webp$/, "");
}

/** The flyer's small square thumbnail (160 px), for the row of an event's posts; its version is the flyer's and the
 * thumbnails' settings. */
export function thumbUrl(media: EventMedia): string | null {
  if (!media.flyer) return null;
  const version = media.version && `${media.version}.${THUMB_SIZE}.${THUMB_QUALITY}`;
  return versioned(`${BASE_URL}thumbs/${thumbName(media.flyer)}.webp`, version);
}

/** A video's short silent clip (the backend's previews/), played in the detail; null without one. */
export function previewUrl(media: EventMedia): string | null {
  return media.preview ? `${BASE_URL}${media.preview}` : null;
}

/**
 * The report form; for an event, with it filled in: "Título (2026-10-03) · <id>", the id to find it. An event over
 * several days gives its days: "Festival (2026-11-13 al 2026-11-15) · <id>"; a series, its sessions: "Intensivo
 * (2026-11-08, 2026-11-22, 2026-11-29, 2026-12-06) · <id>".
 */
export function feedbackUrl(event?: DanceEvent): string {
  if (!event) return FEEDBACK_FORM;
  const days = isSeries(event)
    ? event.sessions.map((session) => session.date).join(", ")
    : isMultiDay(event)
      ? `${event.date} al ${lastDay(event)}`
      : event.date;
  const params = new URLSearchParams({ usp: "pp_url", [FEEDBACK_EVENT_FIELD]: `${event.title} (${days}) · ${event.id}` });
  return `${FEEDBACK_FORM}?${params}`;
}

/** The account's Instagram profile ("https://www.instagram.com/academia/"). */
export function profileUrl(account: string): string {
  return `https://www.instagram.com/${encodeURIComponent(account)}/`;
}

/** Instagram's embed of that profile (its photo, counts and latest posts), shown inside the site (postViewer.ts). */
export function profileEmbedUrl(account: string): string {
  return `https://www.instagram.com/${encodeURIComponent(account)}/embed/`;
}

/** The main post: the one shown on the card and shared by default. */
export function mainMedia(event: DanceEvent): EventMedia {
  return event.media[0];
}

/**
 * Path (under the site root) of the event's link-preview image, made by pages/og/[id].jpg.ts for every event,
 * with its version (`?v=`, linkPreview.ts) so apps that cached an older image fetch the corrected one.
 */
export function previewImagePath(event: DanceEvent, version: string): string {
  return `og/${encodeURIComponent(event.id)}.jpg?v=${version}`;
}

/** Path of the event's own page ("/evento/<id>/"), generated by pages/evento/[id].astro. */
export function eventPath(event: DanceEvent): string {
  return `${BASE_URL}evento/${encodeURIComponent(event.id)}/`;
}

/**
 * The details closed, the address bar should no longer show an event: the home page's address (keeping `search`
 * and `hash`) when `path` is still an event's page, else null (it's already right).
 */
/** Each view's own address: the list is the home page, the calendar /calendario/ (a reload or a shared link stays). */
export function viewPath(view: View): string {
  return view === "calendar" ? `${BASE_URL}calendario/` : BASE_URL;
}

/** The view an address opens on: /calendario/ (with or without its slash) is the calendar, anything else the list. */
export function viewOfPath(pathname: string): View {
  return pathname.replace(/\/?$/, "/") === `${BASE_URL}calendario/` ? "calendar" : "upcoming";
}

/**
 * The address to go back to when the details close on an event's own address: the view's (the list's, the
 * calendar's), keeping the query and the hash. Null when the address is already a view's.
 */
export function addressAfterClosing(
  { pathname, search, hash }: Pick<Location, "pathname" | "search" | "hash">,
  view: View = "upcoming",
): string | null {
  return pathname.startsWith(`${BASE_URL}evento/`) ? `${viewPath(view)}${search}${hash}` : null;
}

/**
 * A shared link's event: `?evento=<id>` (where /evento/<id>/ forwards a browser). Its id, the other parameters
 * (`utm_source=compartido`, kept for the statistics) and the address without it. Null without one.
 */
export function sharedEventLink({ pathname, search, hash }: Pick<Location, "pathname" | "search" | "hash">) {
  const params = new URLSearchParams(search);
  const id = params.get("evento");
  if (!id) return null;
  params.delete("evento");
  const rest = params.toString();
  return { id, params, address: `${pathname}${rest ? `?${rest}` : ""}${hash}` };
}

/** Full URL of the event's page, for sharing and calendars. */
export function eventPageUrl(event: DanceEvent): string {
  return new URL(eventPath(event), SITE_URL).href;
}

export interface EventTimes {
  start: string; // "YYYYMMDD" (all day) or "YYYYMMDDTHHMMSS" (Bogotá local time)
  end: string;
  allDay: boolean;
}

/**
 * Start and end for calendars. Without a start time it's an all-day event; without an end time it
 * lasts DEFAULT_DURATION_HOURS; an end before the start means it finishes after midnight. An event over
 * several days is all day from its first day to its last (the end is exclusive: the day after the last). A workshop
 * series: its first session (each session's own: sessionTimes).
 */
export function eventTimes(event: DanceEvent): EventTimes {
  if (isMultiDay(event)) {
    return { start: event.date.replaceAll("-", ""), end: addDays(lastDay(event), 1).replaceAll("-", ""), allDay: true };
  }
  return dayTimes(event);
}

/** A workshop series' sessions, each with its own times, for calendars: one entry per session. */
export function sessionTimes(event: DanceEvent): EventTimes[] {
  return (event.sessions ?? []).map(dayTimes);
}

/** One day's start and end (an event on one day, or one session). */
function dayTimes({ date, start_time, end_time }: Pick<Session, "date" | "start_time" | "end_time">): EventTimes {
  const day = date.replaceAll("-", "");
  const nextDay = addDays(date, 1).replaceAll("-", "");
  if (!start_time) return { start: day, end: nextDay, allDay: true };

  const startHour = Number(start_time.slice(0, 2));
  const endTime =
    end_time ?? `${String((startHour + DEFAULT_DURATION_HOURS) % 24).padStart(2, "0")}:${start_time.slice(3)}`;
  const endDay = endTime <= start_time ? nextDay : day;
  return {
    start: `${day}T${start_time.replace(":", "")}00`,
    end: `${endDay}T${endTime.replace(":", "")}00`,
    allDay: false,
  };
}

/**
 * The calendar feed's description, one line each: when ("9:00 p. m.", "Hora por confirmar"; an event over several
 * days, its days: "Viernes 13 al domingo 15 de noviembre · 8:00 p. m."; a series' session, which one and every one:
 * "Sesión 2 de 4 · 2:00 p. m.", "4 sesiones: 8, 22, 29 nov y 6 dic"), the price, the account, the event's page.
 */
export function calendarDescription(event: DanceEvent, session?: Session): string[] {
  if (session && isSeries(event)) {
    const which = `Sesión ${event.sessions.indexOf(session) + 1} de ${event.sessions.length}`;
    const when = [which, formatTime(session.start_time) || "hora por confirmar"].join(" · ");
    return [when, eventDaysLabel(event), priceSummary(event), `@${event.account}`, eventPageUrl(event)].filter(Boolean);
  }
  const time = formatTime(event.start_time);
  const when = isMultiDay(event) ? [eventDaysLabel(event), time].filter(Boolean).join(" · ") : time || "Hora por confirmar";
  return [when, priceSummary(event), `@${event.account}`, eventPageUrl(event)].filter(Boolean);
}

/** Text for the location field of the calendar feed and maps. */
export function locationText(event: DanceEvent): string {
  return [event.venue, event.address, event.area, "Bogotá"].filter(Boolean).join(", ");
}

/** Google Maps search for the venue, or null when the post gives no venue or address. */
export function mapsUrl(event: DanceEvent): string | null {
  if (!event.venue && !event.address) return null;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(locationText(event))}`;
}

