// URLs built from an event: flyer image, its own page, Google Maps, the report form, and calendar times.

import type { DanceEvent, EventMedia } from "../types";
import { addDays } from "./dates";

export const BASE_URL = import.meta.env.BASE_URL.replace(/\/?$/, "/");
const SITE_URL = new URL(BASE_URL, import.meta.env.SITE).href; // "https://pa-bailar.github.io/"
const DEFAULT_DURATION_HOURS = 4; // socials often run past midnight
// Reports and ideas go to a Google Form (owned by the site's author): no account needed, answers land in a
// Google Sheet. From an event's detail, its "Evento" question comes filled in (a pre-filled link's entry).
const FEEDBACK_FORM = "https://docs.google.com/forms/d/e/1FAIpQLScMjLlDsXBdgqNGjs3MIBhuMKQhG7xZpdAyzlA5lHxH7OiXtw/viewform";
const FEEDBACK_EVENT_FIELD = "entry.1000168347";

export function flyerUrl(media: EventMedia): string | null {
  return media.flyer ? `${BASE_URL}${media.flyer}` : null;
}

/** "flyers/123-0.webp" → "123-0": the name of its small thumbnail, made by pages/thumbs/[name].webp.ts. */
export function thumbName(flyer: string): string {
  return flyer.replace(/^.*\//, "").replace(/\.webp$/, "");
}

/** The flyer's small square thumbnail (160 px), for the row of an event's posts. */
export function thumbUrl(media: EventMedia): string | null {
  return media.flyer ? `${BASE_URL}thumbs/${thumbName(media.flyer)}.webp` : null;
}

/** A video's short silent clip (the backend's previews/), played in the detail; null without one. */
export function previewUrl(media: EventMedia): string | null {
  return media.preview ? `${BASE_URL}${media.preview}` : null;
}

/** The report form; for an event, with it filled in: "Título (2026-10-03) · <id>", the id to find it. */
export function feedbackUrl(event?: DanceEvent): string {
  if (!event) return FEEDBACK_FORM;
  const params = new URLSearchParams({ usp: "pp_url", [FEEDBACK_EVENT_FIELD]: `${event.title} (${event.date}) · ${event.id}` });
  return `${FEEDBACK_FORM}?${params}`;
}

/** The main post: the one shown on the card and shared by default. */
export function mainMedia(event: DanceEvent): EventMedia {
  return event.media[0];
}

/** Path (under the site root) of the event's link-preview image, made by pages/og/[id].jpg.ts. */
export function previewImagePath(event: DanceEvent): string | null {
  return mainMedia(event).flyer ? `og/${encodeURIComponent(event.id)}.jpg` : null;
}

/** Path of the event's own page ("/evento/<id>/"), generated by pages/evento/[id].astro. */
export function eventPath(event: DanceEvent): string {
  return `${BASE_URL}evento/${encodeURIComponent(event.id)}/`;
}

/** Full URL of the event's page, for sharing and calendars. */
export function eventPageUrl(event: DanceEvent): string {
  return new URL(eventPath(event), SITE_URL).href;
}

export interface EventTimes {
  start: string; // "YYYYMMDD" (all day) or "YYYYMMDDTHHMMSS" (Bogotá local time)
  end: string;
  allDay: boolean;
}

/**
 * Start and end for calendars. Without a start time it's an all-day event; without an end time it
 * lasts DEFAULT_DURATION_HOURS; an end before the start means it finishes after midnight.
 */
export function eventTimes(event: DanceEvent): EventTimes {
  const day = event.date.replaceAll("-", "");
  const nextDay = addDays(event.date, 1).replaceAll("-", "");
  if (!event.start_time) return { start: day, end: nextDay, allDay: true };

  const startHour = Number(event.start_time.slice(0, 2));
  const endTime =
    event.end_time ??
    `${String((startHour + DEFAULT_DURATION_HOURS) % 24).padStart(2, "0")}:${event.start_time.slice(3)}`;
  const endDay = endTime <= event.start_time ? nextDay : day;
  return {
    start: `${day}T${event.start_time.replace(":", "")}00`,
    end: `${endDay}T${endTime.replace(":", "")}00`,
    allDay: false,
  };
}

/** Text for the location field of the calendar feed and maps. */
export function locationText(event: DanceEvent): string {
  return [event.venue, event.address, event.area, "Bogotá"].filter(Boolean).join(", ");
}

/** Google Maps search for the venue, or null when the post gives no venue or address. */
export function mapsUrl(event: DanceEvent): string | null {
  if (!event.venue && !event.address) return null;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(locationText(event))}`;
}

